###################################
##  Uses IFTTT to notify me of bad logins.
###################################

- alias: Login Failure
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.http_login') != 'unknown' }}"

  action:
    service: notify.notify
    data_template:
      message: "Login fehlgeschlagen! ({{ states('persistent_notification.http_login') }})"
      title: "Sicherheit"