###################################
##  New device connected
###################################

- alias: New device connected
  hide_entity: True
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Neues Gerät verbunden'
        value2: '{{trigger.event.data.host_name}}'
        value3: '{{trigger.event.data.entity_id}}'