###################################
##  New device connected
###################################

- alias: New device connected
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    service: notify.notify
    data_template:
      title: "Sicherheit"
      message: "Neues Gerät verbunden. Host: {{trigger.event.data.host_name}}, ID: {{trigger.event.data.entity_id}}"
