###################################
##  Start Up Section
###################################

- alias: Startup Notification
  hide_entity: True
  trigger:
    - platform: homeassistant
      # Event can also be 'shutdown'
      event: start
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Home Assistant gestartet'
        value2: ''
        value3: ''