###################################
##  Start Up Section
###################################

- alias: Startup Notification
  hide_entity: True
  trigger:
    - platform: homeassistant
      # Event can also be 'shutdown'
      event: start
  action:
    service: notify.notify
    data_template:
      message: "Home Assistant gestartet"