- alias: "Tracking Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.p8lite

  action:
    - service: script.ifttt_notify
      data_template:
        value1:  >
          {% if is_state('device_tracker.p8lite', 'home') %}
            Martina ist daheim
          {% else %}
            Martina ist {{ states('device_tracker.p8lite') }}.
          {% endif %}
        value2: ''
        value3: ''  