dist: focal
language: python
python:
  - "3.9"

install:
  - pip3 install homeassistant
script:
  - docker run -d \
    --name homeassistant \
    --privileged \
    --restart=unless-stopped \
    -e TZ=Europe/Vienna \
    -v $TRAVIS_BUILD_DIR:/config \
    --network=host \
    ghcr.io/home-assistant/home-assistant:stable \
    hass -c . --script check_config
before_install:
  - sudo apt-get install -y ffmpeg libudev-dev python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  - mv travis_secrets.yaml secrets.yaml
  - touch travis_cert_fakefile automations.yaml scenes.yaml scripts.yaml
notifications:
  email: false
  webhooks:
    on_error: always
    on_failure: always
    on_start: never
    on_success: never
    on_cancel: never
    