language: python
python:
  - "3.4"
install:
  - pip3 install homeassistant==0.64.3
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch travis_cert_fakefile
notifications:
  email: false