language: python
python:
  - "3.5"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch travis_cert_fakefile
notifications:
  email: false
  webhooks:
    urls:
      - !secret travisci_webhook_url
    on_error: always
    on_failure: always
    on_start: never
    on_success: never
    on_cancel: never
    