homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customize

hassio:

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest

http:
  base_url: !secret http_baseurl
  api_password: !secret api_pass
  ssl_certificate: !secret tls_cert
  ssl_key: !secret tls_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.70.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
   #- google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Define groups
group: !include_dir_merge_named group

# Define device tracker
device_tracker: !include_dir_merge_list device_tracker

logger:
  default: error

# Enables support for tracking state changes over time.
history:
    exclude:
      domains:
        - proximity

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 30
  exclude:
    domains:
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free 
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.transmission_down_speed
      - sensor.transmission_status
      - sensor.transmission_up_speed

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free 
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.transmission_down_speed
      - sensor.transmission_status
      - sensor.transmission_up_speed

# Track the sun
sun:

# Show map in UI
map:

# Light control
light:
  platform: hue
  host: 10.70.0.3

# Text to speech
tts:
  platform: google
  language: 'en'

emulated_hue:
  expose_by_default: false
  exposed_domains:
    - script
  
ifttt:
  key: !secret ifttt_key

# enable wake on lan
wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0

climate:
  - platform: zwave

xiaomi_aqara:
  gateways:
    - host: 10.70.0.7
      mac: !secret aqara_mac
      key: !secret aqara_key

config:

proximity:
  home:
    devices:
      - device_tracker.thomas
    tolerance: 50
    unit_of_measurement: m

history_graph:
  temperature:
    name: temperature
    entities:
      - sensor.temperature_158d0001ab1939
      - sensor.temperature_158d0001db62c4
      - sensor.temperature_158d0001f534ca
      - sensor.temperature_158d0001fa5b0d
    hours_to_show: 24
    refresh: 600
  humidity:
    name: humidity
    entities:
      - sensor.humidity_158d0001ab1939
      - sensor.humidity_158d0001db62c4
      - sensor.humidity_158d0001f534ca
      - sensor.humidity_158d0001fa5b0d
    hours_to_show: 24
    refresh: 600
  transmission:
    entities:
      - sensor.transmission_down_speed
      - sensor.transmission_up_speed
    hours_to_show: 24
    refresh: 600

automation: !include_dir_merge_list automation/
camera: !include_dir_merge_list camera/
media_player: !include_dir_merge_list media_player/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
scene: !include_dir_merge_list scene/
switch: !include_dir_merge_list switch/
#shell_command: !include shell_command.yaml
zone: !include_dir_merge_list zone/
script: !include_dir_merge_named script/
input_boolean: !include_dir_merge_named input_boolean/
