homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_pass
  ssl_certificate: ***REMOVED***
  ssl_key: ***REMOVED***
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Define groups
group: !include_dir_merge_named group

# Define device tracker
device_tracker: !include_dir_merge_list device_tracker

logger:
  default: error

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 7

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.latestcommit
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free 
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.transmission_down_speed
      - sensor.transmission_status
      - sensor.transmission_up_speed

# Track the sun
sun:

# Light control
light:
  platform: hue
  host: philipshue

# Text to speech
tts:
  platform: google
  language: 'en'

mqtt:
  broker: !secret mqtt_host
  port: 22223
  username: !secret mqtt_user
  password: !secret mqtt_pass

emulated_hue:
automation: !include_dir_merge_list automation/
camera: !include_dir_merge_list camera/
media_player: !include_dir_merge_list media_player/
sensor: !include_dir_merge_list sensor/
scene: !include_dir_merge_list scene/
switch: !include_dir_merge_list switch/
shell_command: !include shell_command.yaml
zone: !include_dir_merge_list zone/
