homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 206
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Define groups
group: !include_dir_merge_named group

# Define device tracker
device_tracker: !include_dir_merge_list device_tracker

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Light control
light:
  platform: hue
  host: philipshue

# Text to speech
tts:
  platform: google
  language: 'en'

mqtt:
  broker: m21.cloudmqtt.com
  port: 22223
  username: !secret mqtt_user
  password: !secret mqtt_pass

# media_player: !include_dir_list media_player/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
zone: !include_dir_merge_list zone/
