homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customize
  # auth
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 10.70.0.0/24
  packages: !include_dir_named packages

mobile_app:

zeroconf:

hassio:

system_health:

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy
    - !secret trusted_proxy2
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
   #- google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Define groups
group: !include_dir_merge_named group

logger:
  default: error

# Enables support for tracking state changes over time.
history:
    exclude:
      domains:
        - proximity

recorder:
  db_url: !secret db_url
  purge_keep_days: 10
  exclude:
    domains:
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.last_boot

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free 
      - sensor.last_boot

# Track the sun
sun:

# Show map in UI
map:

# Text to speech
tts:
  platform: google_translate
  language: 'en'

emulated_hue:
  listen_port: 80
  advertise_ip: 10.70.0.9
  advertise_port: 8300
  expose_by_default: false
  exposed_domains:
    - script
    - light

# enable wake on lan
wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0

climate:
  - platform: zwave

config:

proximity:
  home:
    devices:
      - device_tracker.thomas
    tolerance: 50
    unit_of_measurement: m

transmission:
  host: 10.70.0.10
  username: !secret transmission_user
  password: !secret transmission_pass

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

influxdb:
  host: !secret influxdb_host
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - friendly_name
    - device_class
    - node_id
  include:
    entities:
      - group.tracker
    domains:
      - binary_sensor
      - sensor
      - climate
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*battery:
      override_measurement: battery_level
    sensor.*battery_level:
      override_measurement: battery_level

light:
  - platform: switch
    name: Stehlampe
    entity_id: switch.tplinkkasa1

webostv:
  host: 10.70.0.29
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lgtv_mac

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    mode: freedaily

input_number:
counter:
input_datetime:

automation: !include automations.yaml
media_player: !include_dir_merge_list media_player/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
scene: !include scenes.yaml
switch: !include_dir_merge_list switch/
zone: !include_dir_merge_list zone/
script: !include scripts.yaml
input_boolean: !include_dir_merge_named input_boolean/