homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customize
  # auth
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 10.70.0.0/24

hassio:

system_health:

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest

http:
  base_url: !secret http_baseurl
  ssl_certificate: !secret tls_cert
  ssl_key: !secret tls_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
   #- google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Define groups
group: !include_dir_merge_named group

# Define device tracker
device_tracker: !include_dir_merge_list device_tracker

logger:
  default: error

# Enables support for tracking state changes over time.
history:
    exclude:
      domains:
        - proximity

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 30
  exclude:
    domains:
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.last_boot

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sun.sun
      - sensor.pitemperature
      - sensor.disk_use_home
      - sensor.cpu_use
      - sensor.ram_free 
      - sensor.last_boot

# Track the sun
sun:

# Show map in UI
map:

# Light control
hue:
  bridges:
    - host: 10.70.0.3

# Text to speech
tts:
  platform: google_translate
  language: 'en'

emulated_hue:
  listen_port: 80
  advertise_ip: 10.70.0.9
  advertise_port: 8300
  expose_by_default: false
  exposed_domains:
    - script
  entities:
    switch.tvon:
      name: "Fernseher"
      hidden: false
  
ifttt:
  key: !secret ifttt_key

# enable wake on lan
wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0

climate:
  - platform: zwave

xiaomi_aqara:
  gateways:
    - host: 10.70.0.7
      mac: !secret aqara_mac
      key: !secret aqara_key

config:

proximity:
  home:
    devices:
      - device_tracker.thomas
    tolerance: 50
    unit_of_measurement: m

history_graph:
  temperature:
    name: temperature
    entities:
      - sensor.temperature_158d0001ab1939
      - sensor.temperature_158d0001db62c4
      - sensor.temperature_158d0001f534ca
      - sensor.temperature_158d0001fa5b0d
    hours_to_show: 24
    refresh: 600
  humidity:
    name: humidity
    entities:
      - sensor.humidity_158d0001ab1939
      - sensor.humidity_158d0001db62c4
      - sensor.humidity_158d0001f534ca
      - sensor.humidity_158d0001fa5b0d
    hours_to_show: 24
    refresh: 600
  livingroom:
    name: livingroom
    entities:
      - sensor.temperature_158d0001db62c4
      - sensor.humidity_158d0001db62c4
      - sensor.livingroom_is_warm
      - climate.danfoss_thermostat_wohnzimmer_heating_1
    hours_to_show: 24
    refresh: 600

tplink:
  discovery: false
  switch:
    - host: 10.70.0.5

transmission:
  host: 10.70.0.10
  username: !secret transmission_user
  password: !secret transmission_pass

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

automation: !include automations.yaml
automation old: !include_dir_merge_list automation/

camera: !include_dir_merge_list camera/
media_player: !include_dir_merge_list media_player/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
scene: !include_dir_merge_list scene/
switch: !include_dir_merge_list switch/
#shell_command: !include shell_command.yaml
zone: !include_dir_merge_list zone/
script: !include_dir_merge_named script/
input_boolean: !include_dir_merge_named input_boolean/
