- platform: broadlink
  host: 10.70.0.41
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    samsung_tv:
      friendly_name: "Samsung TV Power"
      command_on: 'JgCMAJePFTQWNBY0Fg8WDxYPFg8WDxY0FjQWMxYQFRAVEBYPFg8WDxY0Fg8WDxYPFg8WDxYPFjQW
DxY0FjQVNBY0FjQWNBUABe+WjxY0FjQVNRUPFhAVEBUQFg8WNBU1FTQWDxYPFg8WDxYQFRAVNBYP
FhAVEBUQFRAWDxY0FRAVNBY0FjQWNBU0FjUVAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJePFTQWNBY0Fg8WDxYPFg8WDxY0FjQWMxYQFRAVEBYPFg8WDxY0Fg8WDxYPFg8WDxYPFjQW
DxY0FjQVNBY0FjQWNBUABe+WjxY0FjQVNRUPFhAVEBUQFg8WNBU1FTQWDxYPFg8WDxYQFRAVNBYP
FhAVEBUQFRAWDxY0FRAVNBY0FjQWNBU0FjUVAA0FAAAAAAAAAAAAAAAA'