- platform: template
  switches:
    onkyo:
      value_template: "{{ is_state('media_player.onkyo', 'on') }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.onkyo_receiver
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.onkyo_receiver