- platform: template
  switches:
    tvon:
      value_template: "{{is_state('media_player.onkyo', 'on')}}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_tv
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_tv