# - platform: wake_on_lan
#   name: wake_htpc
#   host: htpc
#   mac: '00-1f-d0-56-b7-0b'
#   turn_off:
#     service: media_player.kodi_call_method
#     data:
#       entity_id: media_player.kodi
#       method: System.Suspend

- platform: wake_on_lan
  name: wake_corei5
  host: 10.70.0.12
  mac: '40-16-7E-AA-DF-0F'

- platform: wake_on_lan
  name: wake_server
  host: 10.70.0.10
  mac: '00-25-90-c8-0d-7c'
