update_config:
  sequence:
      # only if current build is passing
    - condition: state
      entity_id: binary_sensor.travis_status
      state: 'on'
    - service: script.ifttt_notify
      data_template:
        value1: 'Aktualisiere Konfiguration... Build {{states.sensor.travis_build_label}}'
    - service: shell_command.pull_config
    - service: homeassistant.restart