
- alias: turn on living room heating when temp decreases during the day
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_158d0001db62c4
    value_template: '{{ state | float }}'
    above: 0.0
    below: 20.5
    for:
      minutes: 15

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.heating_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      #- condition: time
      #  after: '07:30:00'
      #  before: '00:30:00'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.danfoss_thermostat_wohnzimmer_heating_1
        temperature: 25
        
- alias: turn off living room heating when temp is fine
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_158d0001db62c4
    value_template: '{{ state.attributes.battery }}'
    above: 20.5
    for:
      minutes: 15

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.heating_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.danfoss_thermostat_wohnzimmer_heating_1
        temperature: 20



