
- alias: set heating visibility
  hide_entity: True
  trigger:
    - platform: homeassistant
      event: start
    - platform: sun
      event: sunrise

  condition:
    - condition: template
      value_template: >
         {% if now().month <= 3 or now().month >= 10 %}
           true
         {% endif %}

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.heating_visible