- platform: generic
  name: Thomas
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.thomas_nexus6p.attributes.latitude }},{{ states.device_tracker.thomas_nexus6p.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:Thomas%7C{{ states.device_tracker.thomas_nexus6p.attributes.latitude }},{{ states.device_tracker.thomas_nexus6p.attributes.longitude }}
  limit_refetch_to_url_change: true