- platform: darksky
  api_key: !secret darksky_apikey
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - cloud_cover
    - temperature
    - apparent_temperature