- platform: snmp
  name: wan_in
  host: 10.70.0.1
  baseoid: 1.3.6.1.2.1.2.2.1.10.8
  unit_of_measurement: "bits"

- platform: snmp
  name: wan_out
  host: 10.70.0.1
  baseoid: 1.3.6.1.2.1.2.2.1.16.8
  unit_of_measurement: "bits"

- platform: template
  sensors:
    wan_in_mbps:
      friendly_name: "WAN in"
      value_template: "{{ ((states.input_number.wan_in_delta.state | float ) / 1000000 ) | round(2) }}"
      unit_of_measurement: "Mbps"

- platform: template
  sensors:
    wan_out_mbps:
      friendly_name: "WAN out"
      value_template: "{{ ((states.input_number.wan_out_delta.state | float ) / 1000000 ) | round(2) }}"
      unit_of_measurement: "Mbps"
