- alias: climate group visibility
  hide_entity: True

  trigger:
    - platform: state
      entity_id: input_boolean.heating_mode

  action:
    - service: group.set_visibility
      entity_id: group.climate
      data_template:
        entity_id: group.climate
        visible: >
          {% if is_state('input_boolean.heating_mode', 'on') %}
            true
          {% else %}
            false
          {% endif %}