- alias: relax in living room at night
  trigger:
    - platform: time
      at: '22:30:00'

  condition:
    - condition: state
      entity_id: light.wohnzimmerlicht
      state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_relax