- alias: dimming bed room at night
  hide_entity: False
  trigger:
    - platform: time
      after: '22:00:00'

  condition:
    - condition: state
      entity_id: light.schlafzimmer
      state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.schlafzimmer_relax