- alias: getting home evening
  hide_entity: False
  trigger:
    - platform: state
      entity_id: device_tracker.thomas_nexus6p
      to: 'home'

  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: time
      after: '16:00:00'
      before: '23:59:00'

  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_normal
    - service: light.turn_on
      entity_id: light.vorzimmer
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.vorzimmer