- alias: "motion detected entrance"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001660a33_occupancy
      to: 'on'

  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: template
      value_template: '{% if states.automation.motion_detected_entrance.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.motion_detected_entrance.attributes.last_triggered)) > 60*5 }}  {% else %}  true {% endif %}'

  action:
    - service: light.turn_on
      entity_id: light.vorzimmer
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.vorzimmer


- alias: "motion detected livingroom"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000165ffde_occupancy
      to: 'on'

  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: time
      after: '15:30:00'
      before: '23:59:00'
    - condition: template
      value_template: '{% if states.automation.motion_detected_livingroom.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.motion_detected_livingroom.attributes.last_triggered)) > 60*5 }}  {% else %}  true {% endif %}'

  action:
    - service: light.turn_on
      entity_id: light.wohnzimmerlicht


- alias: "turn off all lights"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00016c39d4
        click_type: long_click_press
    - platform: state
      entity_id: group.tracker
      to: 'not_home'
      for:
        minutes: 5
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{trigger.entity_id != states.group.tracker.entity_id}}'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.all_lights


- alias: "toggle bedroom lights"
  trigger:
    platform: state
    entity_id: sensor.0x00158d00016c39d4_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.schlafzimmerlicht

- alias: "dim bedroom lights"
  trigger:
    platform: state
    entity_id: sensor.0x00158d00016c39d4_click
    to: double
  action:
    - service: light.toggle
      data:
        entity_id: light.schlafzimmerlicht
        transition: true
        brightness: 1

- alias: "toggle living room light"
  trigger:
    platform: state
    entity_id: sensor.0x00158d00015f2421_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.wohnzimmerlicht