- alias: "motion detected entrance"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001660a33
      to: 'on'

  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: time
      after: '16:00:00'
      before: '23:59:00'
    - condition: template
      value_template: '{% if states.automation.motion_detected_entrance.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.motion_detected_entrance.attributes.last_triggered)) > 60*5 }}  {% else %}  true {% endif %}'

  action:
    - service: light.turn_on
      entity_id: light.vorzimmer
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.vorzimmer


- alias: "turn off all lights"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016c39d4
      click_type: long_click_press
  action:
    - service: light.turn_off
      entity_id: group.all_lights


- alias: "toggle bedroom lights"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016c39d4
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.schlafzimmerlicht


- alias: "toggle living room light"
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_158d00015f2421
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.wohnzimmerlicht