- alias: raspi3 offline notification
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.raspi3
    to: 'off'
    for:
      minutes: 20

  action:
    service: script.ifttt_notify
    data_template:
      value1: 'Raspi3 offline'