- alias: switch receiver source on chromecast playing
  hide_entity: False
  trigger:
    - platform: state
      entity_id: media_player.chromie
      to: 'playing'

  action:
    # Turn on Receiver
    - service: media_player.turn_on
      entity_id: media_player.onkyo
    # Switch to Kodi source
    - service: media_player.select_source
      data:
        entity_id: media_player.onkyo
        source: strm-box